#!/usr/bin/env bash
# Display numbers 1 to 20. For the 4th, 9th, and 17th iterations also
# display country specific superstition warning.

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	    4)#!/usr/bin/env bash
# Display hours and minutes for 12 hours and 59 minutes

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo $minute
		((minute++))
	done
	((hour++))
done
		echo bad luck from China
		;;
	    9)
		echo bad luck from Japan
		;;
	    17)
		echo bad luck from Italy
		;;
	esac
	((i++))
done
